import { Facility } from "./types";

/**
 * Mock facilities for development/testing.
 * In production, data comes from D1 via the Worker API.
 * This file is NOT imported in the production code path.
 */
export const MOCK_FACILITIES: Facility[] = [
  {
    id: "1",
    name: "Fitness Park Letná",
    address: "Milady Horákové 16, Praha 7",
    city: "Praha",
    lat: 50.0986,
    lng: 14.4256,
    category: "fitness",
    activities: ["Fitness", "Cardio", "Funkční trénink"],
    activity_summary: "Fitness, Cardio, Funkční trénink",
    image_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop",
    gallery_images: [],
    website_url: "https://fitnesspark.cz",
    phone: "+420 123 456 789",
    email: "info@fitnesspark.cz",
    description: "Moderní fitness centrum s výhledem na Letnou",
    is_new: false,
    recommended: true,
    additional_payment: false,
    additional_payment_desc: null,
    active_cards: [
      { name: "Stříbrná", id: 1, description: "Fitness, Cardio" },
      { name: "Student", id: 4, description: "Fitness, Cardio" },
    ],
    kids_activities: false,
    only_virtual_card: false,
    parking: "Yes",
    self_service: false,
    self_service_times: null,
    unlimited_oh: false,
    facebook_url: null,
    instagram_url: null,
  },
  {
    id: "2",
    name: "Plavecký stadion Podolí",
    address: "Podolská 74, Praha 4",
    city: "Praha",
    lat: 50.0581,
    lng: 14.4234,
    category: "swimming",
    activities: ["Plavání", "Aqua aerobik", "Skoky do vody"],
    activity_summary: "Plavání, Aqua aerobik",
    image_url: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&h=600&fit=crop",
    gallery_images: [],
    website_url: "https://pfraha.cz",
    phone: "+420 234 567 890",
    email: null,
    description: "Legendární plavecký stadion v Podolí",
    is_new: false,
    recommended: false,
    additional_payment: false,
    additional_payment_desc: null,
    active_cards: [
      { name: "Stříbrná", id: 1, description: "Plavání" },
      { name: "Dítě", id: 2, description: "Plavání" },
    ],
    kids_activities: true,
    only_virtual_card: false,
    parking: "Yes",
    self_service: false,
    self_service_times: null,
    unlimited_oh: false,
    facebook_url: null,
    instagram_url: null,
  },
];
